name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      # Check out your repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Docker Buildx (ensures multi-platform builds are supported)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build your custom Buildozer Docker image from your Dockerfile
      - name: Build Buildozer Docker image
        run: |
          docker build --platform linux/amd64 -t kivy/buildozer .

      # Run Buildozer inside the container to build your Android APK
      #
      # Here we mount:
      # - the GitHub workspace into /home/user/src so that the container has your source (and buildozer.spec)
      # - a temporary directory for Buildozer’s cache (~/.buildozer)
      #
      # The working directory (-w) is set to /home/user/src (where your source is)
      - name: Run Buildozer to build APK
        run: |
          docker run --rm \
            -w /home/user/src \
            -v "${{ github.workspace }}:/home/user/src" \
            -v "${{ runner.temp }}/.buildozer:/home/user/.buildozer" \
            kivy/buildozer buildozer android debug

      # (Optional) List output files so you can verify that the APK was generated.
      - name: List output files
        run: ls -la "${{ github.workspace }}/bin"

      # Upload the generated APK artifact (adjust the path as needed)
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: ${{ github.workspace }}/bin/*.apk
